
server:
  port: 27777 #服务端口号，默认无需修改，该参数只在运行data-migrate-app.py 启动单个服务时有效。多进程方式启动时，请在gunicorn.py中配置端口号。
  threads: 100 #线程数，默认无需修改。该参数只在运行data-migrate-app.py 启动单个服务时有效。多进程方式启动时，请在gunicorn.py中配置线程数。

read_tool: # 读数工具专有配置
  oracle:
    mode: thick #oracle连接模式，默认thin模式。如果要使用thick模式，请修改为thick。oracle11g必须使用thick模式并按照oracle客户端。
  oceanbase:
    username: DOUMING
    password: QHv_{0VKiN
    host: t7ql6qlkari3k-mi.aliyun-cn-shenzhen-internet.oceanbase.cloud
    port: 1521
    database: dm_tenant1
    pool_size: 3  # 连接池大小
    app:
      file_gz:
        username: DOUMING
        password: QHv_{0VKiN
        host: t7ql6qlkari3k-mi.aliyun-cn-shenzhen-internet.oceanbase.cloud
        port: 1521
        database: dm_tenant1
        pool_size: 3  # 连接池大小
      file_tzzj:
        username: DOUMING
        password: QHv_{0VKiN
        host: t7ql6qlkari3k-mi.aliyun-cn-shenzhen-internet.oceanbase.cloud
        port: 1521
        database: dm_tenant1
        pool_size: 3  # 连接池大小
      file_rzqs:
        username: DOUMING
        password: QHv_{0VKiN
        host: t7ql6qlkari3k-mi.aliyun-cn-shenzhen-internet.oceanbase.cloud
        port: 1521
        database: dm_tenant1
        pool_size: 3  # 连接池大小
#  oceanbase:
#    username: Y7PHFUND_REALTIME@UAT_GZ01#UAT_Cluster05
#    password: aaAA11##2025
#    host: uatobc05.phfund.com.cn
#    port: 2883
#    database: Y7PHFUND_REALTIME
#    pool_size: 3  # 连接池大小


  file:
    batch:
      process:
        pool:
          size: 10 # 进程池大小。

dbf:
  chunk_size: 10000 #txt文件读取的块大小，默认100000条记录。
  using_multi_process_switch_count: 1000000 # 开启多进程处理的阈值，默认100000条记录。

txt:
  chunk_size: 10000 #txt文件读取的块大小，默认100000条记录。



# 系统是启动多个进程，然后每个进程启动多个线程，每个线程处理一个请求
# 这里是对单个进程的限流配置，控制进程维度处理的并发数，请注意：不是所有进程的总线程数控制。
# 限流次数要小于单个进程的线程数才能生效，否则会导致2个结果：
#  1：这里的配置无效[原因：限流次数都大于系统开辟的线程数，开辟的线程数都在处理请求，无发通过外部调用判断是否触发限流，这样就达不到限流效果]
#  2：外部请求将等待直至超时，得不到及时的响应，也得不到限流反馈，只能得到超时反馈。
limit:
  calls: 9 # 调用次数。 这里建议的配置是：单个进程的线程数-1。  备注:单个进程的线程数在gunicorn.conf.py中配置。
  period: 1 # 单位秒



